### PR TITLE
[WIP] Introduce Puli and PHP-DI configuration file

### PR DESCRIPTION
**Pull request by tgalopin**
This PR aims to introduce Puli into this project in order to simplify the installation process even more for users of DependecyInjection libraries that are compatible with Puli.

It also introduce a PHP-DI configuration file as the library will probably soon support Puli (https://github.com/PHP-DI/PHP-DI/pull/360, https://github.com/PHP-DI/Kernel).

### CODE REVIEW

**Comment by stof** [comment]
IMO, the library should be agnostic of DI containers

**Comment by tgalopin** [comment]
The library will stay DI agnostic : it is just a help to setup the library in PHPDI using Puli. It's a bit the equivalent of the Symfony EventDispatcher bridge, and I would like to create a Symfony DI integration as well in the future :) .

**Comment by jdreesen** [comment]
Wouldn't be the wiki a better place for this "recipe"? Or maybe the docs?

**Comment by tgalopin** [comment]
The useful thing about Puli is it's auto installation of packages with the Composer plugin. When you will install FOSMessage using Composer (`composer require ...`), if you are using PHP-DI and Puli, it will automatically load the configuration file of this PR so the services will be loaded without any action from you (not even an "include"). It's much more powerful than documentation IMO.

I'm not sure of anything on this level for the moment, it's something quite new (PHP-DI is experimenting Puli). Do you think we should not include the PHP-DI integration for the moment?

**Comment by jdreesen** [comment]
It sounds quite useful and I'm aware of PHP-DI's experiments with Puli, but I'm not sure if this should be included directly into this lib. 
But toying around with it a little bit can't hurt ;)

**Comment by tgalopin** [comment]
In fact, the idea I have behind this would be to support a basic integration of the library into any framework without having to create a link package (bundle for Sf, module for ZF, etc.). I think creating a link package for 3 services and a bit of configuration does not worth it and I would like to try to implement this with Puli :) 

It's very expermiental though, so I probably won't merge it soon (I think only PHP-DI supports Puli forthe moment).

**Comment by mccrodp** [comment]
Is there anything that can be done here that would benefit the development of this proposal: https://github.com/FriendsOfSymfony/FOSMessage/issues/19 (Driver for Drupal)? If so, I may have some time to help over the coming weeks. Thanks!

**Comment by stof** [comment]
I think we should keep it out of the library for now, until the team working on PSR-11 at least agrees on an approach to the problem

**Comment by tgalopin** [comment]
I agree with @stof, there have been quite a lot of work on the container-interop side (PSR-11 but also https://github.com/container-interop in general). We should probably wait for this to be ready.

@mccrodp: is the container accessible from plugins in Drupal 8 or is it only for the core? If you can use it in your plugin, it could be a great opprtunity to implement https://github.com/container-interop/service-provider directly into the library so you don't have to do anything (your plugin would be less coupled to the library internal architecture).

**Comment by mccrodp** [comment]
@tgalopin Thanks for your reply. I'm going to do some research into your suggestions and then answer you properly soon, re: Drupal 8.

**Comment by stof** [comment]
@tgalopin the @container-interop organization is the sandbox of the PSR-11 workgroup for their experiments.
I would not rely on any of their experiments, as they are just that: experiments which can change at any time

**Comment by tgalopin** [comment]
Well ... I think that's what I said isn't it?

**Comment by mnapoli** [comment]
Hi everyone! I don't know how I ended up on this issue but that's the magic of the internet I guess :)

That discussion is an interesting use case for https://github.com/container-interop/service-provider indeed (as you mentioned @tgalopin). This experiment is for PSR-11, and it's not stable. However if you have feedback as a potential user of this [not-yet] standard feel free to post it to the project.

> @tgalopin the @container-interop organization is the sandbox of the PSR-11 workgroup for their experiments. I would not rely on any of their experiments, as they are just that: experiments which can change at any time

@stof repositories that are tagged with stable version numbers (eg. 1.0.0) are stable though. The only example for now is https://github.com/container-interop/container-interop which indeed started as an experiment, but today it's used as a stable "standard" (not a PSR yet though, but that doesn't prevent it from being useful). However the "service-provider" is still experimental indeed.

**Pull request closed without merging**
