### PR TITLE
Update sender.rst

### PR DESCRIPTION
**Pull request by MHaendel**

### CODE REVIEW

**Comment by tgalopin** [comment]
Thanks @MHaendel!

Does it fails when you try to use the current documentation? Why do you want to change it here?

EDIT : the following closing is a misclick

**Comment by MHaendel** [comment]
Hi,

The bundle requires a string as a subject, null is not allowed. Missing ) also added.

**Comment by jdreesen** [comment]
The interface allows `null` values as subject: https://github.com/FriendsOfSymfony/FOSMessage/blob/1d3eb96817abb9a99f5e1bcbabd5e3b8f3ea089d/src/SenderInterface.php#L39
And the implementation does so, too: https://github.com/FriendsOfSymfony/FOSMessage/blob/1d3eb96817abb9a99f5e1bcbabd5e3b8f3ea089d/src/Sender.php#L68

**Comment by tgalopin** [comment]
@MHaendel I'm not sure to understand what you mean for the subject, the library does not require a  subject (and there is no bundle for the moment).

I fixed the parenthesis though, thanks!

**Pull request closed without merging**
